import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import { Poppins } from "next/font/google";
import Footer from "@/components/Footer";

const poppins = Poppins({
  weight: "400",
  preload: false,
});

export const metadata = {
  title: "Tile Master Solution",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} body_content`}>
        <div id='home' className={"contact"}>
          <a className={"item_link"} href="#">+999 123 456 789</a>
          <a className={"item_link"} href="#">Email@email.com</a>

          <div className={"social_container"}>
            <a className={"item_link"} href="#"><i className="bi bi-instagram" /></a>
            <a className={"item_link"} href="#"><i className="bi bi-threads" /></a>
            <a className={"item_link"} href="#"><i className="bi bi-tiktok" /></a>
          </div>
        </div>

        <main className="main">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
