import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: "400",
  preload: false,
});

export const metadata = {
  title: "Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} body_content`}>{children}</body>
    </html>
  );
}
